# Generated by Django 5.2.6 on 2025-09-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_candidateprofile_phone_alter_candidateprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'PENDENTE'), ('in_review', 'EM ANÁLISE'), ('approved', 'APROVADO'), ('rejected', 'REPROVADO'), ('interview', 'ENTREVISTA')], max_length=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'ordering': ['application_date'],
            },
        ),
    ]
