# Generated by Django 5.2.6 on 2025-09-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_candidateprofile_phone_alter_candidateprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('localization', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(choices=[('presencial', 'PRESENCIAL'), ('remoto', 'REMOTO'), ('híbrido', 'HÍBRIDO')], max_length=20)),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='accounts.enterprise')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
